fhir:
  mappings:
    modul:
      prostata:
        enabled: true
    patient-reference-generation:
      # -- How the Resource.subject.reference to the Patient resources should be generated.
      # You should set `fhir.mappings.create-patient-resources.enabled=false` when changing this from the default
      # to avoid creating additional, unreferenced Patient resources.
      strategy: PSEUDONYMIZE_AND_LOOKUP_IN_FHIR_SERVER
      fhir-server:
        # -- the base URL of a FHIR server used to lookup an existing logical Patient id from a local identifier.
        # E.g. `https://fhir.example.com/fhir`
        base-url: "https://webhook.site/777032ca-8ae8-402d-a5c3-6b7edd241103"
        auth:
          basic:
            # -- use HTTP Basic Authentication for FHIR server authentication
            enabled: true
            # -- the username
            username: "test"
            # -- the password
            password: "test"
      fhir-pseudonymizer:
        # -- the base URL of the FHIR Pseudonymizer used to pseudonymize the Patient_ID before
        # looking up the actual Patient.id in the FHIR server. Invokes the `$de-identify` operation.
        # E.g. `https://fhir.example.com/fhir`
        base-url: "https://webhook.site/777032ca-8ae8-402d-a5c3-6b7edd241103"
